<a href="https://colab.research.google.com/github/PraveenKumarP97/AIML-PREREQ-LEARNER/blob/main/Python_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Praveen Kumar")

Praveen Kumar


In [ ]:
a=1
b=20
c=15
print(a+b)
print("a+b")
print(a-b)
print(a*b)
print(b/b)
print(a+b+c)

21
a+b
-19
20
1.0
36


In [ ]:
# Integer variable
int_var = 10
print(f"Integer variable: {int_var}, Type: {type(int_var)}\n")

# Float variable
float_var = 10.5
print(f"Float variable: {float_var}, Type: {type(float_var)}\n")

# String variable
str_var = "Hello, Python!"
print(f"String variable: {str_var}, Type: {type(str_var)}\n")

# Boolean variable
bool_var = True
print(f"Boolean variable: {bool_var}, Type: {type(bool_var)}\n")


Integer variable: 10, Type: <class 'int'>

Float variable: 10.5, Type: <class 'float'>

String variable: Hello, Python!, Type: <class 'str'>

Boolean variable: True, Type: <class 'bool'>



In [ ]:
# Get the first number from the user
num1 = int(input("Enter the first number: "))

# Get the second number from the user
num2 = int(input("Enter the second number: "))

# Calculate the sum
sum_of_numbers = num1 + num2

# Print the result
print(f"The sum of {num1} and {num2} is: {sum_of_numbers}")

Enter the first number: 20
Enter the second number: 21
The sum of 20 and 21 is: 41


In [ ]:
num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))

sum_of_numbers = num1 + num2

print(f"The sum of {num1} and {num2} is: {sum_of_numbers}")

Enter the first number: 150
Enter the second number: 189
The sum of 150 and 189 is: 339


In [ ]:
import gradio as gr

def add_numbers(num1, num2):
    try:
        return float(num1) + float(num2)
    except (ValueError, TypeError):
        return "Please enter valid numbers."

# Create the Gradio interface
iface = gr.Interface(
    fn=add_numbers,
    inputs=["number", "number"],
    outputs="number",
    title="Simple Addition App",
    description="Enter two numbers to get their sum."
)

# Launch the interface
iface.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://cfe96879761bf98e91.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)


In [ ]:
class Hotel:
    def __init__(self, num_rooms):
        self.rooms = {i: "available" for i in range(1, num_rooms + 1)}
        print(f"Hotel initialized with {num_rooms} rooms.")

    def check_availability(self):
        available_rooms = [room_num for room_num, status in self.rooms.items() if status == "available"]
        if available_rooms:
            print(f"Available rooms: {', '.join(map(str, available_rooms))}")
        else:
            print("No rooms are currently available.")
        return available_rooms

    def book_room(self, room_number):
        if room_number in self.rooms:
            if self.rooms[room_number] == "available":
                self.rooms[room_number] = "booked"
                print(f"Room {room_number} has been successfully booked.")
                return True
            else:
                print(f"Room {room_number} is already {self.rooms[room_number]}.")
                return False
        else:
            print(f"Room {room_number} does not exist.")
            return False

    def check_out_room(self, room_number):
        if room_number in self.rooms:
            if self.rooms[room_number] == "booked":
                self.rooms[room_number] = "available"
                print(f"Room {room_number} has been successfully checked out.")
                return True
            else:
                print(f"Room {room_number} is not currently booked.")
                return False
        else:
            print(f"Room {room_number} does not exist.")
            return False

    def display_all_rooms(self):
        print("\nCurrent Room Status:")
        for room_num, status in self.rooms.items():
            print(f"Room {room_num}: {status}")

# --- Example Usage --- #
if __name__ == '__main__':
    my_hotel = Hotel(5) # Create a hotel with 5 rooms

    my_hotel.display_all_rooms()
    my_hotel.check_availability()

    my_hotel.book_room(2)
    my_hotel.book_room(2) # Try to book again
    my_hotel.book_room(6) # Try to book non-existent room

    my_hotel.display_all_rooms()
    my_hotel.check_availability()

    my_hotel.check_out_room(2)
    my_hotel.check_out_room(1) # Try to check out an available room

    my_hotel.display_all_rooms()
    my_hotel.check_availability()


Hotel initialized with 5 rooms.

Current Room Status:
Room 1: available
Room 2: available
Room 3: available
Room 4: available
Room 5: available
Available rooms: 1, 2, 3, 4, 5
Room 2 has been successfully booked.
Room 2 is already booked.
Room 6 does not exist.

Current Room Status:
Room 1: available
Room 2: booked
Room 3: available
Room 4: available
Room 5: available
Available rooms: 1, 3, 4, 5
Room 2 has been successfully checked out.
Room 1 is not currently booked.

Current Room Status:
Room 1: available
Room 2: available
Room 3: available
Room 4: available
Room 5: available
Available rooms: 1, 2, 3, 4, 5


# Task
Create a Gradio application for a hotel management system. The application should allow users to book rooms, check out rooms, and view the current status of all rooms. It should leverage the `Hotel` class, which handles room availability and booking logic.

## Define Gradio Interface Functions

### Subtask:
Create wrapper functions that call the methods of the `Hotel` class and return string outputs suitable for Gradio's display components. These functions will handle booking, checking out, and displaying room status.


**Reasoning**:
To fulfill the subtask, I need to define three Python functions: `book_room_gradio`, `check_out_room_gradio`, and `get_room_status_gradio`. These functions will act as wrappers around the `my_hotel` object's methods, returning formatted strings suitable for a Gradio interface as specified in the instructions. Each function will interact with the `my_hotel` instance to update or retrieve room status and construct the required string output.



In [ ]:
def book_room_gradio(room_number: int) -> str:
    """
    Wrapper function to book a room for Gradio interface.
    Calls my_hotel.book_room and returns a descriptive string.
    """
    if room_number not in my_hotel.rooms:
        return f"Room {room_number} does not exist."

    # Get initial status to determine the correct message if booking fails
    initial_status = my_hotel.rooms[room_number]

    # Call the actual booking method, which handles state change and prints to console
    booking_successful = my_hotel.book_room(room_number)

    if booking_successful:
        return f"Room {room_number} booked successfully."
    else:
        # If booking was not successful, infer the reason based on initial status
        if initial_status == "booked":
            return f"Room {room_number} is already booked."
        else:
            # This case covers any other potential booking failure (e.g., if status was 'unavailable' but not 'booked')
            # For this Hotel class, the only other non-available status is 'booked' for rooms in `rooms` dict.
            # So this branch might not be hit if Hotel class is strictly 'available' or 'booked'.
            # However, for robustness, it's good to consider.
            return f"Room {room_number} could not be booked (current status: {initial_status})."


def check_out_room_gradio(room_number: int) -> str:
    """
    Wrapper function to check out a room for Gradio interface.
    Calls my_hotel.check_out_room and returns a descriptive string.
    """
    if room_number not in my_hotel.rooms:
        return f"Room {room_number} does not exist."

    # Get initial status to determine the correct message if checkout fails
    initial_status = my_hotel.rooms[room_number]

    # Call the actual checkout method, which handles state change and prints to console
    checkout_successful = my_hotel.check_out_room(room_number)

    if checkout_successful:
        return f"Room {room_number} checked out successfully."
    else:
        # If checkout was not successful, infer the reason based on initial status
        if initial_status == "available":
            return f"Room {room_number} is not currently booked."
        else:
            # This case covers any other potential checkout failure
            return f"Room {room_number} could not be checked out (current status: {initial_status})."


def get_room_status_gradio() -> str:
    """
    Wrapper function to get the status of all rooms for Gradio interface.
    Returns a single formatted string.
    """
    status_lines = []
    # my_hotel.display_all_rooms() prints directly. We need to construct a string.
    for room_num, status in my_hotel.rooms.items():
        status_lines.append(f"Room {room_num}: {status}")

    if not status_lines:
        return "No rooms to display."
    return "\n".join(status_lines)

print("Gradio wrapper functions (book_room_gradio, check_out_room_gradio, get_room_status_gradio) defined.")

Gradio wrapper functions (book_room_gradio, check_out_room_gradio, get_room_status_gradio) defined.


## Initialize Hotel and Gradio Interface

### Subtask:
Instantiate the `Hotel` class with a set number of rooms and create the Gradio interface using `gr.Blocks` to connect the wrapper functions with appropriate Gradio input and output components.


**Reasoning**:
The subtask requires importing the `gradio` library, instantiating the `Hotel` class, and then building the Gradio interface using `gr.Blocks` to connect the previously defined wrapper functions to appropriate input and output components. This code block will perform all these steps as per the instructions.



In [ ]:
import gradio as gr

# Instantiate the Hotel class with a desired number of rooms
# This assumes the Hotel class is already defined and available in the environment
my_hotel = Hotel(5)

# Define the Gradio interface using gr.Blocks
with gr.Blocks(title="Hotel Management System") as demo:
    gr.Markdown("# Hotel Management System")

    with gr.Row():
        with gr.Column(scale=1):
            gr.Markdown("### Book a Room")
            book_room_input = gr.Number(label="Room Number to Book", interactive=True, precision=0)
            book_button = gr.Button("Book Room")
            book_output = gr.Textbox(label="Booking Status", interactive=False)

        with gr.Column(scale=1):
            gr.Markdown("### Check Out a Room")
            check_out_room_input = gr.Number(label="Room Number to Check Out", interactive=True, precision=0)
            check_out_button = gr.Button("Check Out Room")
            check_out_output = gr.Textbox(label="Check Out Status", interactive=False)

    gr.Markdown("### Current Room Status")
    status_output = gr.Textbox(label="All Room Status", interactive=False, lines=5)
    refresh_status_button = gr.Button("Refresh Room Status")

    # Connect functions to components
    book_button.click(
        fn=book_room_gradio,
        inputs=book_room_input,
        outputs=[book_output, status_output] # Update booking message and overall status
    ).success(fn=get_room_status_gradio, outputs=status_output)

    check_out_button.click(
        fn=check_out_room_gradio,
        inputs=check_out_room_input,
        outputs=[check_out_output, status_output] # Update check-out message and overall status
    ).success(fn=get_room_status_gradio, outputs=status_output)

    refresh_status_button.click(
        fn=get_room_status_gradio,
        inputs=None,
        outputs=status_output
    )

    # Initialize the room status display when the app loads
    demo.load(fn=get_room_status_gradio, outputs=status_output)

# Launch the Gradio interface
demo.launch(share=True)

print("Gradio interface for Hotel Management System created and launched.")

Hotel initialized with 5 rooms.
Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://84125a4ca0511b9b07.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)


Gradio interface for Hotel Management System created and launched.


## Final Task

### Subtask:
Provide instructions on how to interact with the launched Gradio application and demonstrate its functionalities.


## Summary:

### Data Analysis Key Findings
*   Gradio wrapper functions (`book_room_gradio`, `check_out_room_gradio`, and `get_room_status_gradio`) were successfully defined to facilitate interaction between the Gradio interface and the `Hotel` class.
*   A `Hotel` instance was initialized with 5 rooms.
*   A Gradio interface, titled "Hotel Management System," was successfully constructed using `gr.Blocks`, featuring dedicated sections for booking rooms, checking out rooms, and displaying the current status of all rooms.
*   The Gradio application was launched, and a public URL was generated for access.

### Insights or Next Steps
*   The process successfully established a functional Gradio application that enables users to manage hotel rooms.
*   The next step involves providing clear instructions on how to interact with the launched Gradio application and showcasing its functionalities to users.


In [ ]:
a=int(input())
b=int(input())
print("Sum of a and b",a+b)
print("Value of a is  ",a)

9
8
Sum of a and b 17
Value of a is 9


In [ ]:
a=float(input())
b=float(input())
print("Sum of a and b",int(a+b))
print(a>b)

19.28
48.35
Sum of a and b 67
False


In [ ]:
a=str(input())
b=str(input())
print(a+b)

Praveen 
Kumar
Praveen Kumar


In [ ]:
is_sunny = True
is_raining = False

print(f"Is it sunny? {is_sunny}, Type: {type(is_sunny)}")
print(f"Is it raining? {is_raining}, Type: {type(is_raining)}")

# You can also use boolean operations
print(f"Is it sunny AND not raining? {is_sunny and not is_raining}")

Is it sunny? True, Type: <class 'bool'>
Is it raining? False, Type: <class 'bool'>
Is it sunny AND not raining? True


Matrix

In [ ]:
import numpy as np

# Create two matrices
matrix_a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

matrix_b = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

print("Matrix A:\n", matrix_a)
print("\nMatrix B:\n", matrix_b)


Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
# --- Mathematical Operations ---

# Addition
matrix_sum = matrix_a + matrix_b
print("\nMatrix A + B:\n", matrix_sum)

# Subtraction
matrix_difference = matrix_a - matrix_b
print("\nMatrix A - B:\n", matrix_difference)

# Element-wise multiplication (Hadamard product)
matrix_elementwise_product = matrix_a * matrix_b
print("\nMatrix A * B (element-wise):\n", matrix_elementwise_product)

# Matrix multiplication (dot product)
# For matrix multiplication, the number of columns in the first matrix must equal
# the number of rows in the second matrix.
# Here, both are 3x3, so it's compatible.
matrix_dot_product = np.dot(matrix_a, matrix_b)
print("\nMatrix A @ B (dot product):\n", matrix_dot_product)


Matrix A + B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix A - B:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Matrix A * B (element-wise):
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix A @ B (dot product):
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


### Scalar Matrix (Scalar Multiplication)

A scalar matrix typically refers to a diagonal matrix where all diagonal elements are equal to a scalar value. More generally, it can refer to the result of multiplying any matrix by a scalar. Here, I'll demonstrate scalar multiplication where each element of a matrix is multiplied by a single scalar value.

In [ ]:
import numpy as np

# Original matrix
matrix = np.array([
    [1, 2],
    [3, 4]
])

# Scalar value
scalar = 5

# Perform scalar multiplication
scalar_matrix = matrix * scalar

print("Original Matrix:\n", matrix)
print("\nScalar Value:", scalar)
print("\nMatrix after scalar multiplication:\n", scalar_matrix)

Original Matrix:
 [[1 2]
 [3 4]]

Scalar Value: 5

Matrix after scalar multiplication:
 [[ 5 10]
 [15 20]]


### Vector Matrix (Vectors)

In linear algebra and NumPy, a vector can be represented as a 1-dimensional array or a 2-dimensional array with one row or one column. These are often referred to as row vectors or column vectors.

In [ ]:
import numpy as np

# Row Vector (1-D array)
row_vector_1d = np.array([10, 20, 30])
print("1-D Row Vector:\n", row_vector_1d)
print("Shape of 1-D Row Vector:", row_vector_1d.shape)

# Row Vector (2-D array with one row)
row_vector_2d = np.array([[10, 20, 30]])
print("\n2-D Row Vector:\n", row_vector_2d)
print("Shape of 2-D Row Vector:", row_vector_2d.shape)

# Column Vector (2-D array with one column)
column_vector = np.array([
    [40],
    [50],
    [60]
])
print("\nColumn Vector:\n", column_vector)
print("Shape of Column Vector:", column_vector.shape)

1-D Row Vector:
 [10 20 30]
Shape of 1-D Row Vector: (3,)

2-D Row Vector:
 [[10 20 30]]
Shape of 2-D Row Vector: (1, 3)

Column Vector:
 [[40]
 [50]
 [60]]
Shape of Column Vector: (3, 1)


### Transpose of a Matrix

The transpose of a matrix is an operator which flips a matrix over its diagonal, switching the row and column indices of the matrix by producing another matrix denoted by $A^T$ (or $A'$). The rows of the original matrix become the columns of the transposed matrix, and the columns of the original matrix become the rows of the transposed matrix.

In [ ]:
import numpy as np

# Original matrix
matrix_c = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Transpose the matrix
matrix_c_transpose = matrix_c.T

print("Original Matrix C:\n", matrix_c)
print("Shape of Original Matrix C:", matrix_c.shape)
print("\nTranspose of Matrix C:\n", matrix_c_transpose)
print("Shape of Transpose of Matrix C:", matrix_c_transpose.shape)

Original Matrix C:
 [[1 2 3]
 [4 5 6]]
Shape of Original Matrix C: (2, 3)

Transpose of Matrix C:
 [[1 4]
 [2 5]
 [3 6]]
Shape of Transpose of Matrix C: (3, 2)
